# Generated by Django 2.1.5 on 2019-01-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='koty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=120)),
                ('kraj', models.CharField(max_length=120)),
                ('czy_gruby', models.BooleanField()),
            ],
        ),
    ]
